### ISSUE TITLE
OSC emails [discussions] 

### ISSUE THREAD

**Issue by souravcipher** [Open-Source-Collective/docs#16]
Just noticed - currently, 3 emails are shared in the docs and used for communications/support.

-  hello [at] oscollective.org - [(docs page url)
](https://docs.oscollective.org/#contact-us)
- support [at] oscollective.org - [(docs page url)
](https://docs.oscollective.org/#contact-us)
- contact [at] oscollective.org - [(docs page url)
](https://docs.oscollective.org/#contact-us)

Also, On the page below, support [at] opencollective.com is mentioned 

- https://docs.oscollective.org/guides/accepting-event-funds

Here on the page - [Employment, Payroll and Benefits](https://docs.oscollective.org/what-we-offer/employment-payroll-and-benefits#worker-classification) the contact us email is the contact [at] opencollective.foundation and [template](https://docs.oscollective.org/what-we-offer/employment-payroll-and-benefits#requirements-and-policies) is the OCF employment agreement template.

**Comment by souravcipher** [comment]
Q.1 Which is the main email to use for contacting OSC for support? (though assuming all the emails go to Freshdesk)
Q.2 Is the Employment, Payroll and Benefits page outdated?

@RichardLitt @poohlaga

**Comment by RichardLitt** [comment]
1. The main email for support should be support@oscollective.org. They all go through Freshdesk. 
2. Yes. We're working on it. Emails should go to contact@oscollective.org.

**Comment by RichardLitt** [comment]
I've changed that .foundation email. Thanks for raising this, Sourav. 

Working on the template with @poohlaga.

**Comment by souravcipher** [comment]
Thank you! 🤘

**Comment by souravcipher** [comment]
Hi @RichardLitt one of my emails failed for the email: contact@oscollective.org

Could you please confirm if it's operational or maybe I have mistaken with a type!! 

![image](https://user-images.githubusercontent.com/72210541/230839435-6be2f0b3-be40-4f2e-8ae5-98591e218af4.png)

**Comment by RichardLitt** [comment]
Huh. You're right - contact@oscollective.org doesn't exist. It should be hello@oscollective.org. Changing it now.

**Comment by RichardLitt** [comment]
Thanks, Sourav.
